In [1]:
matriz_A = [[1, 2, 3,], [4, 5, 6]]

In [2]:
matriz_A

[[1, 2, 3], [4, 5, 6]]

In [3]:
matriz_A[0] # acessando a primeira linha --> NO PYTHON O ÍNDICE COMEÇA DP ZERO

[1, 2, 3]

In [4]:
matriz_A[1] # acessando a segunda linha

[4, 5, 6]

In [5]:
matriz_A[0][1]

2

Usa listas aninhadas como matriz funciona para tarefas computacionais simple, no entando, existe uma maneira melhor de trabalhar com matrizes em Python usando o pacote NumPy

NumPy Array: NumPy

NumPy é um pacote para computação ciêntifica que fornece uma ampla gama de funçãoes e metódos para trabalhar com matrizes multidemensionais.

In [10]:
import numpy as np
matriz_b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

matriz_b
matriz_b.T
matriz_b.T.T
matriz_b.T.T.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [13]:
matriz_b[0] # Acessando a primeira linha

array([1, 2, 3])

In [14]:
matriz_b[2][1] # acessar a terceira da segunda coluna

8

Algumas operações que podemos realizar em matrizes usando o NumPy

* Transposição de matriz
Atranposição de uma matriz é uma operação que tro as linha pelas colunas. Por exemplo se tivermos A com dimensão m x n, a transposta de A é uma matriz B com dimensão n x m, o o elementos na linha i e coluna j de B é o elemento na linha j e coluna i de A.

In [16]:
matriz_transposta = matriz_b.transpose()
matriz_transposta

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

* Adição de matrizes:

A adição e subtração de matrizes são realizadas elemento po elemento. Para que duas mastrizes possam ser adicionadas ou subtraídas, elas devem ter a mesma dimensão m x n, a soma de A e B é uma matriz C, onde cada elemento de C é a soma dos elementos correspondentes de A e B.

In [17]:
matriz1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matriz2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

matriz1 + matriz2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

* Subtração de matrizes

In [18]:
matriz1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matriz2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

matriz1 - matriz2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

A multiplicação de matriz é um pouco mais complexa. A multiplicação de duas matrizes A e B é definida apenas se número de colunas da PRIMEIRA MATRIZ for igual ao número de linhas de SEGUNDA MATRIZ. O resultado de multiplicação é uma matriz C, onde o elemento na linha i e a coluna j é produto escalar da linha i de A e da coluna j de B

In [24]:
matriz1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matriz2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

np.dot(matriz1, matriz2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [23]:
matriz_A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matriz_B = np.array([[1, 2], [3, 4], [5, 6]])

matriz_A.dot(matriz_B)

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])

Novamente, para multiplicar as matrizes A e B, precisamos garantir que o número de colunas da matriz A seja igual ao número de linhas da matriz B. Neste caso, a matriz A tem dimensão m por n e a matriz B tem dimensão n por p, então podemos multiplicá-las.

Para realizar a multiplicação, precisamos multiplicar cada elemento da primeira linha da matriz A pelos elementos correspondentes da primeira coluna da matriz B e somar os produtos. Em seguidas, fazemos o mesmo para a segunda linha da matriz A e a segunda coluna matriz B. O resultado é uma matriz C com o número de linhas da matriz A e o número de colunas da matriz B.

* Divisão de matrizes

Tecnicamente, a divisão de matrizes não existe. Em vez disso, é necessário multiplicar um matriz pelo inverso da outra. Por exemplo, se tivermos duas matrizes A e B, a divisão de A por B seria escrita como A * B^1. Para calcular a divisão de matrizes,, a matriz B deve ser quadrada e seu determinante deve ser diferente de zero. Caso contrário, a divisão não é possível.

Conclusão
* Álgebra linear é um ramo da matemática que está atrelado a resolução de problemas computacionais e estatísticos;
* Utilzar a ferramenta matemática + programação nos dá precisão e agilidade nos resultados.
* Aprender um básico sobre matrizes e propriedades nos levam a compreender o que vem de conteúdos posteriores.